### ISSUE TITLE
Media extended not working for YouTube video

### ISSUE THREAD

**Issue by jostid** [PKM-er/media-extended#173]
All other links works for me, but not this one. Why?

https://youtu.be/PMmHln9JkGM

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/79133398/204092624-07ce7794-aa48-4e20-a57a-85e251029c00.png">

Thanks!
Jostid

**Comment by sawft99** [comment]
I use youtube.com links with no issues.

**Comment by ironhak** [comment]
Hello, I've the same problem. Apparently it does this only for some links, you can try replicate this:
- This video to me works: `![video](https://youtu.be/ABV_7BEslX8)`
- This video does not work: `![video](https://www.youtube.com/watch?v=mqKb5c9Aqwk)`

Hopefully someone can undersatnd why some videos works and other don't.

**Comment by aidenlx** [comment]
Apologies for the long period of inactivity on this project. I wanted to inform you that the plugin has been fully rewritten for the v3 release. I'm currently preparing for the beta release. Once it's available, if you encounter similar issues, please don't hesitate to open a new issue. Thank you for your understanding.

**Comment by aidenlx** [comment]
It's mainly due to obsidian handling of iframe. You can see that this issue persist in obsidian native iframe embeds for some of popular video with copyright limit: `![never gonna give you up](https://www.youtube.com/watch?v=dQw4w9WgXcQ)`, which is caused by [obsidian handling of iframe request](https://stackoverflow.com/questions/72554810/cant-play-some-youtube-videos-through-iframe) that I cannot fix directly. However, in upcoming v3, webpage view that mimic a regular browser should work as a workaround.
