### ISSUE TITLE
[FR] Allow specifying the path to screenshots and add support for videos embedded in documents

### ISSUE THREAD

**Issue by PennHui666** [PKM-er/media-extended#262]
## summary of issue
- Screenshots can currently only be saved to the default path where attachments are stored.
- Videos embedded in documents through preview links such as: ![[test.mp4]] do not support shortcut keys to capture timestamps/timestamped screenshots

## Suggest improvements
- Added settings for custom screenshot storage path (relative to the root directory)
- Supports taking timestamps/screenshots of embedded videos within documents so that they can be operated directly in the context of the same document tab without the need for left and right split screens.

**Comment by aidenlx** [comment]
> Added settings for custom screenshot storage path (relative to the root directory)

impl in v3.0.5-beta.1

> Supports taking timestamps/screenshots of embedded videos within documents so that they can be operated directly in the context of the same document tab without the need for left and right split screens.

I want to clarify that taking timestamps from embedded videos will not be supported in version 3 by design, due to implementation complexity. However, I understand the importance of this feature for enhancing user experience. I encourage you to open a [separate discussion](https://github.com/PKM-er/media-extended/discussions/categories/ideas) to better illustrate the problem and propose a potential solution. This will allow us to explore the feasibility and consider it for future updates.
